on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train_model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Make npm run install
      run: | 
        npm install puppeteer
        npx puppeteer browsers install chrome

    - name: Install Python dependencies
      run: |
        pip install pillow
        pip install transformers
        pip install torch
        pip install datasets

    - name: Run puppeteer
      run: |
        npm run loop
        ls -la ./images/
        cat ./dataset.json
      
    - name: Train OCR model
        python3 ./OCR/train.py

# Le make file ressemble Ã 
#all: install run

#install:
#	npm run install
#	pip install pillow
#	pip install transformers
#	pip install torch
#	pip install datasets
#
#run:
#	npm run loop
#	python3 ./OCR/train.py
