on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - dataset_result.json

jobs:
  train_model:
    runs-on: ubuntu-latest
    outputs:
      model_uploaded: ${{ steps.check_model.outputs.model_uploaded }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Make npm run install
      run: | 
        npm install puppeteer
        npx puppeteer browsers install chrome

    - name: Install Python dependencies
      run: |
        pip install pillow
        pip install transformers
        pip install transformers[torch]
        pip install torch
        pip install datasets

    - name: Run puppeteer
      run: |
        node scrapper.js --loop=50 --cleanup --restart-dataset
        ls -la ./img/
        cat ./dataset.json

    - name: Check if model exists
      id: check_model
      run: |
        if [ -d "trocr-finetuned/" ] && [ "$(ls -A trocr-finetuned/)" ]; then
          echo "model_uploaded=true" >> $GITHUB_OUTPUT
        else
          echo "model_uploaded=false" >> $GITHUB_OUTPUT
        fi

      # Télécharger l'artefact s'il existe
    - name: Download artifact
      if: ${{ steps.check_artifact.outputs.model_uploaded == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: trocr-model
        path: trocr-finetuned/
      
    - name: Train OCR model
      if: ${{ steps.check_model.outputs.model_uploaded == 'false' }}
      run: python3 ./OCR/train.py

    - name: Upload trained model
      if: ${{ steps.check_model.outputs.model_uploaded == 'false' }}
      uses: actions/upload-artifact@v4
      with:
        name: trocr-model
        path: trocr-finetuned/  # dossier contenant ton modèle

# Le make file ressemble à
#all: install run

#install:
#	npm run install
#	pip install pillow
#	pip install transformers
#	pip install torch
#	pip install datasets
#
#run:
#	npm run loop
#	python3 ./OCR/train.py
